# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf2cf10437e3ee6be4602b717e5897f33d77302d4a85b76410d1c0858d46770c4726d987cc9f57ae16106509dc223b4202f52dfa4b9935f748ef2f53dfcd7a30

test:
  secret_key_base: 4d4aef8514e28d6df7c1847645ab8fd83f557d5a3d2d9504128476cb1b7f9a33eb45d6beb5baf64969da41c341994829e95004070f1856945046d6536a091a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
